### ISSUE TITLE
error NU1202: Package Microsoft.CST.DevSkim.CLI 0.6.30 is not compatible with net5.0

### ISSUE THREAD

**Issue by ugreg** [microsoft/DevSkim-Action#12] opened 2022-10-19 14:49 UTC
Using the latest version of DevSkim from [the marketplace](https://github.com/marketplace/actions/devskim). Appears there is some error at the container level with the version of .NET currently in use? This is blocking the running of the credential scanner, as it does not get past the container build step as seen below.

![image](https://user-images.githubusercontent.com/8151045/196724614-4471e91b-441b-4920-ae22-8049e71c00f9.png)

Would like to understand from the team:

1. If my understanding of the root cause is correct.
2. What the ETA could be for a possible fix.

Main error
`error NU1202: Package Microsoft.CST.DevSkim.CLI 0.6.30 is not compatible with net5.0 (.NETCoreApp,Version=v5.0) / any.`

Full logs
```ps
2022-10-19T13:38:56.1474333Z ##[group]Build container for action use: '/home/runner/work/_actions/microsoft/DevSkim-Action/v1/Dockerfile'.
2022-10-19T13:38:56.1546159Z ##[command]/usr/bin/docker build -t 8d5581:3e1307436a9040f584f24b9b70bf9ed8 -f "/home/runner/work/_actions/microsoft/DevSkim-Action/v1/Dockerfile" "/home/runner/work/_actions/microsoft/DevSkim-Action/v1"
2022-10-19T13:38:59.8229167Z Sending build context to Docker daemon  15.36kB
2022-10-19T13:38:59.8230417Z 
2022-10-19T13:38:59.8675939Z Step 1/6 : FROM mcr.microsoft.com/dotnet/sdk:5.0
2022-10-19T13:39:00.0103722Z 5.0: Pulling from dotnet/sdk
2022-10-19T13:39:00.0517866Z c1ad9731b2c7: Pulling fs layer
... ugreg REDACTED this line, redundant pulling, checksum and download messages
2022-10-19T13:39:11.4445762Z 5fdeb3a38fe8: Pull complete
2022-10-19T13:39:12.0050784Z d395fb0767b4: Pull complete
2022-10-19T13:39:12.0168144Z Digest: sha256:3ff465d940de3e2c727794d92fd7bb649c498d4abd91bc9213ea7831ebf01f1e
2022-10-19T13:39:12.0189908Z Status: Downloaded newer image for mcr.microsoft.com/dotnet/sdk:5.0
2022-10-19T13:39:12.0214633Z  ---> 9fec788bd1f9
2022-10-19T13:39:12.0216753Z Step 2/6 : RUN mkdir /tools
2022-10-19T13:39:12.0603980Z  ---> Running in 84fe85f5fa45
2022-10-19T13:39:13.0600997Z Removing intermediate container 84fe85f5fa45
2022-10-19T13:39:13.0601823Z  ---> 6ff498ad6abb
2022-10-19T13:39:13.0602441Z Step 3/6 : RUN dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli
2022-10-19T13:39:13.0913160Z  ---> Running in c98636eb89c9
2022-10-19T13:39:15.5122045Z error NU1202: Package Microsoft.CST.DevSkim.CLI 0.6.30 is not compatible with net5.0 (.NETCoreApp,Version=v5.0) / any. Package Microsoft.CST.DevSkim.CLI 0.6.30 supports: net6.0 (.NETCoreApp,Version=v6.0) / any
2022-10-19T13:39:15.5664737Z [91mThe tool package could not be restored.
2022-10-19T13:39:15.5665497Z Tool 'microsoft.cst.devskim.cli' failed to install. This failure may have been caused by:
2022-10-19T13:39:15.5667394Z 
2022-10-19T13:39:15.5668640Z * You are attempting to install a preview release and did not use the --version option to specify the version.
2022-10-19T13:39:15.5669254Z * A package by this name was found, but it was not a .NET tool.
2022-10-19T13:39:15.5670037Z * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
2022-10-19T13:39:15.5670556Z * You mistyped the name of the tool.
2022-10-19T13:39:15.5670806Z 
2022-10-19T13:39:15.5671133Z For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
2022-10-19T13:39:15.7004363Z The command '/bin/sh -c dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli' returned a non-zero code: 1
2022-10-19T13:39:15.7004743Z [0m
2022-10-19T13:39:15.7031316Z ##[warning]Docker build failed with exit code 1, back off 4.447 seconds before retry.
2022-10-19T13:39:20.1482621Z ##[command]/usr/bin/docker build -t 8d5581:3e1307436a9040f584f24b9b70bf9ed8 -f "/home/runner/work/_actions/microsoft/DevSkim-Action/v1/Dockerfile" "/home/runner/work/_actions/microsoft/DevSkim-Action/v1"
2022-10-19T13:39:20.1724357Z Sending build context to Docker daemon  15.36kB
2022-10-19T13:39:20.1725407Z 
2022-10-19T13:39:20.2150291Z Step 1/6 : FROM mcr.microsoft.com/dotnet/sdk:5.0
2022-10-19T13:39:20.2156462Z  ---> 9fec788bd1f9
2022-10-19T13:39:20.2157067Z Step 2/6 : RUN mkdir /tools
2022-10-19T13:39:20.2227429Z  ---> Using cache
2022-10-19T13:39:20.2231264Z  ---> 6ff498ad6abb
2022-10-19T13:39:20.2232251Z Step 3/6 : RUN dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli
2022-10-19T13:39:20.2500754Z  ---> Running in 97ff5607382d
2022-10-19T13:39:22.6238381Z error NU1202: Package Microsoft.CST.DevSkim.CLI 0.6.30 is not compatible with net5.0 (.NETCoreApp,Version=v5.0) / any. Package Microsoft.CST.DevSkim.CLI 0.6.30 supports: net6.0 (.NETCoreApp,Version=v6.0) / any
2022-10-19T13:39:22.6741674Z [91mThe tool package could not be restored.
2022-10-19T13:39:22.6742248Z Tool 'microsoft.cst.devskim.cli' failed to install. This failure may have been caused by:
2022-10-19T13:39:22.6742498Z 
2022-10-19T13:39:22.6742711Z * You are attempting to install a preview release and did not use the --version option to specify the version.
2022-10-19T13:39:22.6743255Z * A package by this name was found, but it was not a .NET tool.
2022-10-19T13:39:22.6743610Z * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
2022-10-19T13:39:22.6743936Z * You mistyped the name of the tool.
2022-10-19T13:39:22.6744087Z 
2022-10-19T13:39:22.6744569Z For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
2022-10-19T13:39:22.8116855Z The command '/bin/sh -c dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli' returned a non-zero code: 1
2022-10-19T13:39:22.8147421Z [0m
2022-10-19T13:39:22.8149351Z ##[warning]Docker build failed with exit code 1, back off 4.102 seconds before retry.
2022-10-19T13:39:26.9156793Z ##[command]/usr/bin/docker build -t 8d5581:3e1307436a9040f584f24b9b70bf9ed8 -f "/home/runner/work/_actions/microsoft/DevSkim-Action/v1/Dockerfile" "/home/runner/work/_actions/microsoft/DevSkim-Action/v1"
2022-10-19T13:39:26.9381933Z Sending build context to Docker daemon  15.36kB
2022-10-19T13:39:26.9384742Z 
2022-10-19T13:39:26.9816405Z Step 1/6 : FROM mcr.microsoft.com/dotnet/sdk:5.0
2022-10-19T13:39:26.9820016Z  ---> 9fec788bd1f9
2022-10-19T13:39:26.9820655Z Step 2/6 : RUN mkdir /tools
2022-10-19T13:39:26.9843774Z  ---> Using cache
2022-10-19T13:39:26.9844447Z  ---> 6ff498ad6abb
2022-10-19T13:39:26.9845645Z Step 3/6 : RUN dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli
2022-10-19T13:39:27.0330548Z  ---> Running in 4714cc515152
2022-10-19T13:39:29.3897211Z error NU1202: Package Microsoft.CST.DevSkim.CLI 0.6.30 is not compatible with net5.0 (.NETCoreApp,Version=v5.0) / any. Package Microsoft.CST.DevSkim.CLI 0.6.30 supports: net6.0 (.NETCoreApp,Version=v6.0) / any
2022-10-19T13:39:29.4428787Z [91mThe tool package could not be restored.
2022-10-19T13:39:29.4429236Z Tool 'microsoft.cst.devskim.cli' failed to install. This failure may have been caused by:
2022-10-19T13:39:29.4429494Z 
2022-10-19T13:39:29.4429948Z * You are attempting to install a preview release and did not use the --version option to specify the version.
2022-10-19T13:39:29.4430390Z * A package by this name was found, but it was not a .NET tool.
2022-10-19T13:39:29.4430792Z * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
2022-10-19T13:39:29.4431149Z * You mistyped the name of the tool.
2022-10-19T13:39:29.4431312Z 
2022-10-19T13:39:29.4431568Z For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
2022-10-19T13:39:29.5822355Z The command '/bin/sh -c dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli' returned a non-zero code: 1
2022-10-19T13:39:29.5858154Z [0m
2022-10-19T13:39:29.5859499Z ##[endgroup]
2022-10-19T13:39:29.5974320Z ##[error]Docker build failed with exit code 1
2022-10-19T13:39:29.6134258Z Uploading runner diagnostic logs
2022-10-19T13:39:29.6772247Z Completed runner diagnostic log upload
2022-10-19T13:39:29.6772498Z Cleaning up orphan processes
```

**Comment by MCWertGaming** [comment] 2022-10-19 15:40
I have the same error.

**Comment by BernieWhite** [comment] 2022-10-19 16:12
This looks to be a duplicate of #10 although is more descriptive of the issue.

**Closed** 2022-10-19 16:20 UTC
